def digest(seq, site, cut_pos):
    cuts = []
    i = 0
    while True:
        i = seq.find(site, i)
        if i == -1:
            break
        cuts.append(i + cut_pos)
        i += 1
    if not cuts:
        return [len(seq)], [], 0
    fragments = []
    prev = 0
    for c in cuts:
        fragments.append(c - prev)
        prev = c
    fragments.append(len(seq) - prev)
    return fragments, cuts, len(cuts)

def gel(fragments):
    out = ""
    for f in sorted(fragments, reverse=True):
        out += f"{f:>5} bp | " + "#" * (f * 3) + "\n"
    return out

seq = ("ATGCGTACGATCGATCGGATCCGAATTCGCTAGCTAGGCCGATCGATCGTAGCTAGCTAGCTAACGATCGATTCGGCCGATCGATCGTAGCTAGCTAGCTAGCGATCGATTCGATCGGATCCTAGCTAGCTCGATCGATCGGCCGATCGTAGCTAGCTAGCTAACGATCGATCGATCGATCGATTCGATCGATCGATCGGATCCGATCGTAGCTAGCTAGCTAACGATCGATCGATCGATCGGCCGATCGTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCGATCGATTCGATCGATCGATCGATCGTAGCTAGCTAGCTAGCTAGCTAACGATCGGCCGATCGATCGTAGCTAGCTAGCTAGCTAACGATCGATCGATCGATCGGATCCGATCGATCGTAGCTAGCTAGCTAGCTAGCTAGCGATCGGCCGATCGATCGATCGAATTCGATCGATCGTAGCTAGCTAGCTAACGATCGATCGATCGATCGATCGATCGTAGCTAGCTAGCTAGCTAGCGATCGGCCGATCGATCGATCGATCGTAGCTAGCTAGCTAGCTAACGATCGATTCGATCGATCGATCGGATCCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCGATCGATCGATCGATCGATCGATCGGCCGATCGATCGATCGATCGATCGATCGTAGCTAGCTAACGATCGATCGATCGATCGATCGATCGATCGATCGGATCCGATCGTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCGATCGATCGATCGATCGATCGATCGATCGGCCGATCGATCGATCGATCGATCGTAGCTAGCTAGCTAGCTAGCTAGCTAACGATCGATCGATCGATCGATCGATCGATCGTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAACGATCGATCGATCGATCGATCGGCCGATCGATCGATCGATCGATCGATCGTAGCTAGCTAGCTAGCTAGCTAACGATCGATCGATCGATCGATCGATCGATCGATCGATCGTAGCTAGCTAGCTAGCTAGCTAGCTAGCGATCGATCGATCGATCGATCGATCGATCGATCG")

enzymes = {
    "EcoRI": ("GAATTC", 1),
    "BamHI": ("GGATCC", 1),
    "HindIII": ("AAGCTT", 1),
    "TaqI": ("TCGA", 1),
    "HaeIII": ("GGCC", 2)
}

print("\nRunning Restriction Digest Simulation...\n")

for name, (site, cut_pos) in enzymes.items():
    fragments, cuts, count = digest(seq, site, cut_pos)
    print(f"===== {name} Digest =====")
    print(f"Recognized sequence: {site}")
    print(f"Number of cleavages: {count}")
    print(f"Cut positions: {cuts}")
    print(f"Fragment sizes: {fragments}")
    print("Simulated gel:")
    print(gel(fragments))
